from pathlib import Path
p=Path('app/src/main/java/com/albasil/inventory/MainActivity.java')
s=p.read_text(encoding='utf-8')
needle='        body.addView(scanRow);\n\n        barcode.setOnEditorActionListener'
insert='''        body.addView(scanRow);\n\n        Button manualAdd = wideButton("+   مادة جديدة", Color.rgb(16, 163, 74), Color.WHITE);\n        manualAdd.setOnClickListener(v -> manualItemDialog(session));\n        body.addView(manualAdd, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, dp(54)));\n        body.addView(space(10));\n\n        barcode.setOnEditorActionListener'''
if needle not in s: raise SystemExit('insert point not found')
s=s.replace(needle,insert,1)
marker='    private void startScanner() {'
method='''    private void manualItemDialog(InventorySession session) {\n        LinearLayout box = new LinearLayout(this);\n        box.setOrientation(LinearLayout.VERTICAL);\n        box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);\n        box.setPadding(dp(22), dp(8), dp(22), dp(4));\n\n        EditText name = input("اسم المادة *");\n        EditText code = input("الكود");\n        EditText barcode = input("الباركود");\n        EditText unit = input("الوحدة");\n        unit.setText("وحدة");\n        EditText group = input("المجموعة");\n        EditText qty = input("الكمية *");\n        qty.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);\n        qty.setText("1");\n        CheckBox saveMaterial = new CheckBox(this);\n        saveMaterial.setText("حفظ المادة ضمن قائمة المواد");\n        saveMaterial.setChecked(false);\n\n        box.addView(name); box.addView(code); box.addView(barcode);\n        box.addView(unit); box.addView(group); box.addView(qty); box.addView(saveMaterial);\n\n        AlertDialog dlg = new AlertDialog.Builder(this)\n                .setTitle("إضافة مادة جديدة")\n                .setView(box)\n                .setNegativeButton("إلغاء", null)\n                .setPositiveButton("إضافة", null)\n                .create();\n        dlg.setOnShowListener(x -> dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v -> {\n            String nm = name.getText().toString().trim();\n            if (nm.isEmpty()) { name.setError("أدخل اسم المادة"); return; }\n            double q;\n            try { q = Double.parseDouble(qty.getText().toString().trim().replace(',', '.')); }\n            catch (Exception e) { qty.setError("أدخل كمية صحيحة"); return; }\n\n            MaterialItem m = new MaterialItem();\n            m.id = "manual_" + UUID.randomUUID();\n            m.name = nm;\n            m.code = code.getText().toString().trim();\n            m.barcode = barcode.getText().toString().trim();\n            m.unit = val(unit.getText().toString(), "وحدة");\n            m.group = val(group.getText().toString(), "مواد يدوية");\n            materials.add(m);\n            session.counts.put(m.key(), q);\n            if (!saveMaterial.isChecked()) prefs.edit().putString("temp_" + m.id, session.id).apply();\n            saveData();\n            dlg.dismiss();\n            showInventory(session);\n        }));\n        dlg.show();\n        name.requestFocus();\n    }\n\n'''
if marker not in s: raise SystemExit('marker not found')
s=s.replace(marker,method+marker,1)
p.write_text(s,encoding='utf-8')
print('manual item patch ready')
